### ISSUE TITLE
Package broken on Master

### ISSUE THREAD

**Issue by iamEtornam** [gurleensethi/sailor#34]
I updated my Flutter SDK to

```
Flutter 1.15.4-pre.274 • channel master • https://github.com/flutter/flutter.git
Framework • revision cbbb7ec5a7 (14 hours ago) • 2020-03-04 12:40:15 -0800
Engine • revision 90bd6f8148
Tools • Dart 2.8.0 (build 2.8.0-dev.11.0 5701c4fd3b)
```

Then i got this when trying to run my project

```
Compiler message:
[   +2 ms] ../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sailor-0.6.0/lib/src/sailor.dart:509:9: Error: No named parameter with the name
'isInitialRoute'.
[        ]         isInitialRoute: settings.isInitialRoute,
[        ]         ^^^^^^^^^^^^^^
[        ] ../../../Development/flutter/packages/flutter/lib/src/widgets/navigator.dart:419:9: Context: Found this candidate, but the arguments don't match.
[        ]   const RouteSettings({
[        ]         ^^^^^^^^^^^^^
[+2956 ms] 
                    Compiler message:
[        ] ../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sailor-0.6.0/lib/src/sailor.dart:509:9: Error: No named parameter with the name
'isInitialRoute'.
[        ]         isInitialRoute: settings.isInitialRoute,
[        ]         ^^^^^^^^^^^^^^
[        ] ../../../Development/flutter/packages/flutter/lib/src/widgets/navigator.dart:419:9: Context: Found this candidate, but the arguments don't match.
[        ]   const RouteSettings({
[        ]         ^^^^^^^^^^^^^
[+4452 ms] Persisting file store
[   +9 ms] Done persisting file store
[   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] Failed to build bundle.
[        ] Error launching application on iPhone 11 Pro Max.
[  +14 ms] "flutter run" took 14,128ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by 3ph** [comment]
Duplicate of https://github.com/gurleensethi/sailor/issues/26

**Comment by Kiruel** [comment]
https://api.flutter.dev/flutter/widgets/RouteSettings/isInitialRoute.html Is now a boolean, and have now a name https://api.flutter.dev/flutter/widgets/RouteSettings/name.html.

**Comment by deadsoul44** [comment]
Any update?

**Comment by pishguy** [comment]
how can i solve this problem? is library updated for this issue?

**Comment by deadsoul44** [comment]
Replace sailor in pubspec.yaml with the following part:
```
  sailor:
    git:
      url: git://github.com/Kiruel/sailor.git
      ref: master
```
You don't need any other change. 
Thanks to @Kiruel

**Comment by hawkbee1** [comment]
Do we know when it will be published on pub.dev?

**Comment by deadsoul44** [comment]
There is no reaction from @gurleensethi . We need to use @Kiruel 's version until this package is updated on pub.dev. The worse thing is that there is an upcoming breaking change in Flutter Navigator 2.0.

**Comment by gurleensethi** [comment]
@RegNex @Kiruel @deadsoul44 @MahdiPishguy @hawkbee1 
Sorry for the delay. I have released `0.7.0` with the fix.

**Comment by peterson-umoke** [comment]
> @RegNex @Kiruel @deadsoul44 @MahdiPishguy @hawkbee1
> Sorry for the delay. I have released `0.7.0` with the fix.

its not still workin the issue still persists.

**Comment by deadsoul44** [comment]
It is working for me. Be sure that the package is updated. Check pubspec.lock.

**Comment by peterson-umoke** [comment]
> It is working for me. Be sure that the package is updated. Check pubspec.lock.

okay, what flutter channel are you in, cause even in this repo, the issue still persists because of the return statement.
check this [link](https://github.com/gurleensethi/sailor/blob/1a05f870f00d86f7ba58aa0e69cec1447c211ba9/lib/src/sailor.dart#L429).

**Comment by deadsoul44** [comment]
I am in flutter beta channel.

**Comment by peterson-umoke** [comment]
no wonder, switch your channel to stable, and you will see it will not work.

**Comment by deadsoul44** [comment]
Probably, breaking change in flutter navigator api is not reached to flutter stable reached. You can switch to beta if you have no other problem for now.

**Comment by peterson-umoke** [comment]
nah, there is a reason its called stable channel, i dont need things breaking my production app all the same i have sent a pull request to the author, lets see if he can merge it.

**Comment by deadsoul44** [comment]
You can use older version. This issue was about the package broken on master.
